#!/usr/bin/env ruby

require 'thor'
require_relative '../lib/todo'

class TodoCLI < Thor
  desc 'list', 'List all tasks'
  def list
    puts todo.list_tasks.to_json

    task = todo.list_tasks.first
    puts "Title: #{task[:title]}, description: #{task[:description]}, #{task[:done]}"
  rescue TodoError => e
    puts "ERROR: #{e.message}"
  end

  desc 'find', 'Find task by ID'
  def find(id)
    task = todo.find_task id

    return if task.nil?

    puts task.to_json
  rescue TodoError => e
    puts "ERROR: #{e.message}"
  end

  desc 'delete', 'Delete task by ID'
  def delete(id)
    deleted_task = todo.delete_task id

    return if deleted_task.nil?

    puts deleted_task.to_json
  rescue TodoError => e
    puts "ERROR: #{e.message}"
  end

  desc 'create TITLE', 'Create task with TITLE'
  option :description, desc: 'Description of the task'
  option :done, type: :boolean, desc: 'Task as done'
  option :undone, type: :boolean, desc: 'Task as undone'

  def create(title)
    attributes = {}
    attributes[:description] = options[:description] if options[:description]

    if options[:done] && options[:undone]
      return
    elsif options[:done]
      attributes[:done] = true
    elsif options[:undone]
      attributes[:done] = false
    end

    new_task = todo.create_task(title, **attributes)

    return if new_task.nil?

    puts new_task.to_json
  rescue TodoError => e
    puts "ERROR: #{e.message}"
  end

  desc 'edit ID', 'Edit task by ID'
  option :title, desc: 'New title'
  option :description, desc: 'New description'
  option :done, type: :boolean, desc: 'Task as done'
  option :undone, type: :boolean, desc: 'Task undone'

  def edit(id)
    attributes = {}
    attributes[:title] = options[:title] if options[:title]
    attributes[:description] = options[:description] if options[:description]

    if options[:done] && options[:undone]
      return
    elsif options[:done]
      attributes[:done] = true
    elsif options[:undone]
      attributes[:done] = false
    end
    return if attributes.empty?

    edit_task = todo.edit_task(id, **attributes)
    return if edit_task.nil?

    puts edit_task.to_json
  rescue TodoError => e
    puts "ERROR: #{e.message}"
  end

  no_commands do
    def todo
      @todo ||= Todo.new storage
    end

    def storage
      @storage ||= MemoryStorage.new([
        { id: '123',
          title: 'Call the vet',
          description: 'appointment for vaccines',
          done: false, },
        {
          id: '567',
          title: 'Go to the store',
          description: 'buy vegetables',
          done: true,
        },
      ])
    rescue TodoFileReadError => e
      puts "ERROR: #{e.message}"
    end
  end
end
TodoCLI.start ARGV
